super::macros::define_type! {
pub [Type, QType, Unknown]:
    A => 1,
    NS => 2,
    MD => 3,
    MF => 4,
    CNAME => 5,
    SOA => 6,
    MB => 7,
    MG => 8,
    MR => 9,
    NULL => 10,
    WKS => 11,
    PTR => 12,
    HINFO => 13,
    MINFO => 14,
    MX => 15,
    TXT => 16,
    OPT => 41,

    [AXFR => 252],
    [MAILB => 253],
    [MAILA => 254],
    [ALL => 255],
}
